diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
core.editor="C:\Users\salak\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
user.name=Salahhh12
user.email=salakh2002tech@gmail.com
safe.directory=%(prefix)///wsl.localhost/Ubuntu/home/salahhh12/Projet-BTC2
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
branch.main.vscode-merge-base=origin/main
